services:
  web:
    container_name: "web"
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/usr/src/app

  db:
    container_name: "mysql"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10

  bot:
    container_name: "bot"
    build:
      context: ./bot
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - ./bot:/usr/src/app
    depends_on:
      - db
    ports:
      - 8001:8001

  # phpmyadmin:
  #   container_name: "phpmyadmin"
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: password
  #     PMA_ARBITRARY: 1
  #   depends_on:
  #     - db

volumes:
  mysql:
